# Site
title: Harsh Modhera
description: "The only way to do great work is to love what you do. —Steve Jobs" 
url: https://misterharsh.github.io
logo: halve-small.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/home.png                 # this image will be shown on homepage's left block
  post-list: images/post.png                # this image will be shown on post list page
  default-post: images/study.png            # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-111952086-1

# Social Links
email:              hkmodhera@gmail.com
#google.plus:       username
#twitter:           username
#facebook:          username
github:             misterharsh 
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           hkmodhera
#xing:              username
#instagram:         username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username
resume:             ./resume_fa17.pdf

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
